Assignment/Models/CourseController.cs
namespace Assignment.Models
{
    public class Product
    {
        public string Title { get; set; }
        public string Author { get; set; }
        public decimal OriginalPrice { get; set; }
        public decimal CurrentPrice { get; set; }
        public int Hours { get; set; }
        public double Rating { get; set; }
        public int RatingsCount { get; set; }
    }
}

Assignment/Controllers/CourseController.cs
using Assignment.Models;
using Microsoft.AspNetCore.Mvc;

namespace Assignment.Controllers
{
    public class CourseController : Controller
    {
        public IActionResult Coures()
        {
            var product = new Product  
            {
                Title = "Blender Character Creator v2.0 for Video Games Design",
                Author = "Ralph Edwards",
                OriginalPrice = 18.99m,
                CurrentPrice = 44.99m,
                Hours = 160,
                Rating = 92.0,
                RatingsCount = 3100
            };
            return View(product);
        }
    }
}

Assignment/Controllers/DefaultController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Assignment.Controllers;

[Authorize]
public class DefaultController : Controller
{
  
    public IActionResult Home()
    {
        return View();
    }
}

Assignment/Views/Course/Coures.cshtml
@{
    ViewData["Title"] = "Courses";
}
<section class="courses"> 
    <div class="container">
        <div class="header">
            <nav class="course-home-menu">
                <a asp-action="Home" asp-controller="Default">Home</a>
                <a asp-action="Coures" asp-controller="Coures">Courses</a>
            </nav>
            <h2>Courses</h2>
            <form class="filter">
                <div class="select">
                    <div class="selected">All categories</div>
                    <div class="select-options">
                        <div class="option" data-value="all">All categories</div>
                        @if (Model.Categories != null)
                        {
                            @foreach (var category in Model.Categories)
                            {
                                <div class="option" data-value="@category.CategoryName">@category.CategoryName</div>
                            }
                        }
                    </div>
                </div>

                <div class="input-search-group">
                    <input id="searchQuery" name="searchQuery" placeholder="Search courses" />
                    <i class="fa-regular fa-search"></i>
                </div>

            </form>


        </div>

    </div>
</section>